### ISSUE TITLE
[FEATURE] Add civbreak

### ISSUE THREAD

**Issue by peef609** [3arthqu4ke/3arthh4ck#217] opened 2022-09-03 04:46 UTC

**Comment by 3arthqu4ke** [comment] 2022-09-03 05:59
Duplicate of #102 also Megyn added Speedmine Instant and CrystalBomber I am just not sure how well they work.

**Comment by master7720** [comment] 2022-09-03 06:00
> Duplicate of #102 also Megyn added Speedmine Instant and CrystalBomber I am just not sure how well they work.

cev and civ are both different things

**Closed by 3arthqu4ke** 2022-09-03 05:59 UTC
Labels: enhancement

**Comment by 3arthqu4ke** [comment] 2022-09-03 06:34
Enlighten me, no description has been provided.
