### ISSUE TITLE
crashes on launch

### ISSUE THREAD

**Issue by jaydonjrl** [3arthqu4ke/3arthh4ck#8] opened 2022-04-16 22:44 UTC

**Comment by jaydonjrl** [comment] 2022-04-16 22:44
it said : The game crashed whilst initializing game
Error: java.lang.UnsatisfiedLinkError: no jassimp in java.library.path
Exit Code: -1

**Comment by master7720** [comment] 2022-04-17 00:25
add a default config into modules folder then add your config(change the name) then go into any servers and type +config module load yourconfigname

**Comment by jaydonjrl** [comment] 2022-04-17 02:06
> add a default config into modules folder then add your config(change the name) then go into any servers and type +config module load yourconfigname

can u be a bit more specific and what if u already have a default. config

**Comment by razedftw** [comment] 2022-04-17 03:03
im getting the same issue if you figure it out plz lmk

**Comment by master7720** [comment] 2022-04-17 03:28
> > add a default config into modules folder then add your config(change the name) then go into any servers and type +config module load yourconfigname
> 
> can u be a bit more specific and what if u already have a default. config

hm weird it fixed it for me when i just added a file called "default.json" in the modules folder

**Comment by threevt** [comment] 2022-04-17 05:26
Send full crash log

**Comment by jaydonjrl** [comment] 2022-04-17 15:37
> Send full crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/17/22 10:36 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: no jassimp in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jassimp.JassimpLibraryLoader.loadLibrary(JassimpLibraryLoader.java:63)
	at jassimp.Jassimp.loadLibrary(Jassimp.java:317)
	at jassimp.Jassimp.importFile(Jassimp.java:124)
	at jassimp.Jassimp.importFile(Jassimp.java:108)
	at me.earth.earthhack.impl.util.render.model.ModelUtil.loadModel(ModelUtil.java:123)
	at me.earth.earthhack.impl.managers.client.FileManager.handleModelDir(FileManager.java:146)
	at me.earth.earthhack.impl.managers.client.FileManager.init(FileManager.java:73)
	at me.earth.earthhack.impl.managers.client.FileManager.<init>(FileManager.java:47)
	at me.earth.earthhack.impl.managers.Managers.<clinit>(Managers.java:78)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:28)
	at net.minecraft.client.Minecraft.handler$zzl000$initHook2(Minecraft.java:45155)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jassimp.JassimpLibraryLoader.loadLibrary(JassimpLibraryLoader.java:63)
	at jassimp.Jassimp.loadLibrary(Jassimp.java:317)
	at jassimp.Jassimp.importFile(Jassimp.java:124)
	at jassimp.Jassimp.importFile(Jassimp.java:108)
	at me.earth.earthhack.impl.util.render.model.ModelUtil.loadModel(ModelUtil.java:123)
	at me.earth.earthhack.impl.managers.client.FileManager.handleModelDir(FileManager.java:146)
	at me.earth.earthhack.impl.managers.client.FileManager.init(FileManager.java:73)
	at me.earth.earthhack.impl.managers.client.FileManager.<init>(FileManager.java:47)
	at me.earth.earthhack.impl.managers.Managers.<clinit>(Managers.java:78)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:28)
	at net.minecraft.client.Minecraft.handler$zzl000$initHook2(Minecraft.java:45155)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by razedftw** [comment] 2022-04-17 15:42
> 

I get the same thing

**Comment by 3arthqu4ke** [comment] 2022-04-17 19:02
Duplicate of #6 for now just clear your earthhack/models folder.

**Closed by 3arthqu4ke** 2022-04-17 19:02 UTC
