### ISSUE TITLE
[FEATURE] add a new bind system with extra buttons

### ISSUE THREAD

**Issue by amendoa657** [3arthqu4ke/3arthh4ck#122] opened 2022-08-22 03:14 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 3arthqu4ke** [comment] 2022-08-22 06:37
Duplicate of #97

**Closed by 3arthqu4ke** 2022-08-22 06:37 UTC
Labels: enhancement
