### ISSUE TITLE
[BUG] Viewmodel not working with future

### ISSUE THREAD

**Issue by nossravgni** [3arthqu4ke/3arthh4ck#63] opened 2022-05-08 15:22 UTC
The Viewmodel module is a bit messy when playing with Future.

"OffHand-X" Doesn't do anything at all but "MainHand-X" seems to be fine.
The "Angle-Translate" is fucked and so is the "Translate" settings.

**Comment by 3arthqu4ke** [comment] 2022-05-08 16:01
Duplicate of #24. Just use Futures Viewmodel? If theirs is missing features I might consider it.

**Closed by 3arthqu4ke** 2022-05-08 16:01 UTC
Labels: bug

**Comment by nossravgni** [comment] 2022-05-08 16:03
I like 3arthh4cks more so it would be nice if it was fixed.
